name: démo outputs
run-name: "Exécution du workflow ${{github.workflow}} pour le commit ${{github.event.head_commit.message}}"
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    step:
      - id: first
        name: Set VAR1
        run: echo "VAR1=Hello" >> $GITHUB_OUTPUT
      - id: second
        name: Set VAR2
        run: echo "VAR2=world" >> $GITHUB_OUTPUT
      - id: third
        name: echo VAR1 VAR2
        run: echo ${{ steps.first.outputs.VAR1 }} ${{ steps.first.outputs.VAR2 }}
