name: démo outputs
run-name: "Exécution du workflow ${{github.workflow}} pour le commit ${{github.event.head_commit.message}}"
on: push
jobs:
  job-1:
    name: Génére des param de sortie
    runs-on: ubuntu-latest
    outputs: # Définit les outputs de job-1 sortie-1 et sortie-2 en les mappants avec mes ouptus VAR1 de first et VAR2 de second
      sortie-1: ${{ steps.first.outputs.VAR1 }}
      sortie-2: ${{ steps.second.outputs.VAR2 }}
    steps:
      - id: first
        name: Set VAR1
        run: echo "VAR1=Hello" >> $GITHUB_OUTPUT
      - id: second
        name: Set VAR2
        run: echo "VAR2=world" >> $GITHUB_OUTPUT
      - id: third
        name: echo VAR1 VAR2
        run: echo ${{ steps.first.outputs.VAR1 }} ${{ steps.second.outputs.VAR2 }}
  job-2:
    name: Récupère les param de job-1
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: echo sortie-1 sortie-2
        run: echo ${{ needs.job-1.outputs.sortie-1 }} ${{ needs.job-1.outputs.sortie-2 }}
